### ISSUE TITLE
Please support building on android iOS device

### ISSUE THREAD

**Issue by codingwatching** [codingminecraft/StreamMinecraftClone#1]
Hi @codingminecraft 
I am very impressed with your youtube content
I think this code and YouTube series will awesome too!
If you can please support this code to build for android and ios devices!
Thank you so much!

**Comment by codingminecraft** [comment]
Hey @codingwatching I appreciate your interest in the project. Unfortunately I don't plan on making this code run on Android and IOS devices. That would require quite a radical change in the way the code works, since I can't expect the same performance specifications as I would get on a PC or console. So, I don't have any plans for this unfortunately :)

**Comment by codingwatching** [comment]
Thank you @codingminecraft !
