### ISSUE TITLE
Pre-Release 0.5 Crash Bug

### ISSUE THREAD

**Issue by Mr-Rudy** [codingminecraft/StreamMinecraftClone#5]
When i start up Pre-Release 0.5 it gives me a error in the command line and shows a black screen
![black screen](https://user-images.githubusercontent.com/88906732/142736111-5fe1a3aa-7ce7-4aa4-9114-fdd410e98491.PNG)
![error](https://user-images.githubusercontent.com/88906732/142736114-fbd52f0f-988e-453a-8d68-7782f512e7d8.PNG)

**Comment by codingminecraft** [comment]
So this warning shouldn't actually be an issue in terms of starting the game, but you may be missing the proper OpenGL drivers. If your computer supports OpenGL 4.6 you should get a window up and running. If you do have OpenGL 4.6 and you're still not getting a window, it would be great if I could see the whole log from the command prompt :)

You can check if your computer supports OpenGL 4.6 by installing this http://www.realtech-vr.com/home/glview/ which is recommended in this SuperUser Q&A https://superuser.com/questions/298443/how-can-i-tell-if-opengl-is-installed-on-a-windows-machine .

I'll be adding an error message in the next Pre-Release that will automatically detect if you have the proper driver support, so you shouldn't be getting a blank console in the future

**Comment by Mr-Rudy** [comment]
So, i have OpenGL 4.6 support and it still shows here the entire command prompt window
![command 1](https://user-images.githubusercontent.com/88906732/142772660-e61b0a61-2475-4d66-afff-5e69e31b5275.PNG)
![command 2](https://user-images.githubusercontent.com/88906732/142772662-f8b9b85a-f557-4338-a473-dc95024287d4.PNG)
![command 3](https://user-images.githubusercontent.com/88906732/142772664-752c2557-aefc-43bd-bff5-5935b7edc005.PNG)

**Comment by codingminecraft** [comment]
This is pretty strange. It looks like all the major initialization components succeeded. I'll have to add more error logs in the next release that way I can hopefully detect what's going wrong here. I know we have a member in the Discord community who must be facing a similar issue, so once I get that resolved and add a new pre-release I'll have to check back in. 

I'll leave this issue open for now, and I'll update it once I add a new pre-release :)

**Comment by Mr-Rudy** [comment]
Ok, thanks

**Comment by codingminecraft** [comment]
This should be resolved in PreRelease0.6 . There were some issues on certain hardware where the GPU would display a black screen. If you're still interested in this, you can download it and let me know if it's fixed in the latest pre release. If not, I'll close this in a few days, thanks again for the help though!

**Comment by Mr-Rudy** [comment]
the bug still happens in PreRelease 0.6

**Comment by codingminecraft** [comment]
Oof. Just when I thought I had it solved haha. If you could let me know what your PC specs are that would also be cool. I'm assuming you're on windows since you downloaded the binaries, but it would also be useful to know what CPU, GPU you have, and whether you're running a laptop or desktop.

Sorry it's still not working too, but I appreciate the help :)

**Comment by Mr-Rudy** [comment]
by tinkering with some settings i got the game to run on pre release 0.6 but when changing it on pre release 0.5 it crashes so u did fix it i just had to changes some stuff
